### ISSUE TITLE
Cool modules

### ISSUE THREAD

**Issue by svimanet** [svimanet/chatbot#11]
Preferably modules taking 1 string input, returns 1 output and can be used in a chatbot. 
Anything goes.

**Comment by YuechengWu** [comment]
Hi, I would like to have a crack at this and add one maybe couple cool modules if it's ok, thanks.

**Comment by YuechengWu** [comment]
Hi @svimanet, do you want us to create the module from scratch or I can use modules I found that is interesting?

**Comment by svimanet** [comment]
@YuechengWu doesn't have to be anything original, as long as can be used in a chatbot, takes an input and returns and output :)
