### ISSUE TITLE
Hactoberfest contributions welcome!

### ISSUE THREAD

**Issue by svimanet** [svimanet/chatbot#21]

**Comment by Exoceus** [comment]
I would love to add a Wikipedia Summarizer.

**Comment by svimanet** [comment]
Contributions does not have to be directly related to any open issues, these are just some alternatives. Imagination is the limit! Also check out the CONTRIBUTING.md [here](https://github.com/svimanet/chatbot/blob/master/docs/CONTRIBUTING.md)
