### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by svimanet** [svimanet/chatbot#65]
The current README is not very informative, nor does it have a good structure. Steps for launching the bot and details about its modules could be useful information.

**Comment by ChaseBosman** [comment]
Ill go ahead and start working on this if that's alright.

**Comment by svimanet** [comment]
I'll leave the task open for future enhancements. 
New modules and features would require updates.

Perhaps automating feature and command documentation in tests and readme could be a fun issue for anyone looking for a slight challenge?

**Comment by ChaseBosman** [comment]
> 
> 
> I'll leave the task open for future enhancements.
> New modules and features would require updates.
> 
> Perhaps automating feature and command documentation in tests and readme could be a fun issue for anyone looking for a slight challenge?

It seems that this would require something such as creating a description function for each module that returns the instructions for using that specific module. If you have a better way of going about it I'd be open to taking that on, but in the meantime I'll take it on from that direction.
